<?php

namespace Modules\System\Providers;

use Modules\Common\Events\UploadedEvent;
use Modules\System\Console\AsyncTask;
use Modules\System\Console\Commands\CleanupLogsCommand;
use Modules\System\Console\ConnectorFrequencyWarning;
use Modules\System\Console\ConnectorLogRecord;
use Modules\System\Console\StatisticsConnectorLog;
use Modules\System\Events\ConnectorLogEvent;
use Modules\System\Listeners\ConnectorLogListener;
use Modules\System\Listeners\ReportExceptionListener;
use Modules\System\Listeners\UploadedListener;
use Modules\System\Support\Configure;
use XditnModule\Events\ReportException;
use XditnModule\Providers\XditnModuleModuleServiceProvider;

class SystemServiceProvider extends XditnModuleModuleServiceProvider
{
    protected array $commands = [
        AsyncTask::class, // 异步任务
        ConnectorLogRecord::class, // 接口日志消费任务
        ConnectorFrequencyWarning::class, // 接口告警通知
        StatisticsConnectorLog::class, // 接口日志统计
        CleanupLogsCommand::class, // 清理过期日志
    ];

    protected array $events = [
        // 异常监听
        ReportException::class => ReportExceptionListener::class,
        // 上传成功事件监听
        UploadedEvent::class => UploadedListener::class,
        // 接口日志记录
        ConnectorLogEvent::class => ConnectorLogListener::class,
    ];

    public function boot(): void
    {
        // 在测试环境中，跳过配置加载，避免数据库连接问题
        $env = env('APP_ENV', config('app.env', 'local'));
        if ($env === 'testing' || $this->app->runningInConsole() && $this->app->runningUnitTests()) {
            // 测试环境中跳过配置加载
            return;
        }

        // 加载动态配置到 Laravel 系统的 Config 中
        try {
            (new Configure())->loadToLaravelConfig($this->app->make('config'));
        } catch (\Exception $e) {
            // 如果配置加载失败，记录日志但不中断应用启动
            \Log::warning('System config load failed: '.$e->getMessage());
        }

        // 开启接口日志记录
        if (config('xditn.system_api_log')) {
            $this->events[ConnectorLogEvent::class] = ConnectorLogListener::class;
        }
    }

    /**
     * route path.
     */
    public function moduleName(): string
    {
        // TODO: Implement path() method.
        return 'system';
    }

    public function configPath(): string
    {
        return parent::configPath(); // TODO: Change the autogenerated stub
    }
}
