<?php

use Illuminate\Database\Seeder;
use Modules\Common\Support\ImportPermissions;

return new class() extends Seeder {
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run(): void
    {
        $menus = $this->menus();

        ImportPermissions::import($menus);
    }

    public function menus(): array
    {
        return  [
            0 => [
                'id' => 205,
                'parent_id' => 0,
                'permission_name' => '域名管理',
                'route' => '/domain',
                'icon' => 'globe-europe-africa',
                'module' => 'domain',
                'permission_mark' => '',
                'component' => '',
                'redirect' => null,
                'keepalive' => 1,
                'type' => 1,
                'hidden' => 1,
                'sort' => 1,
                'active_menu' => '',
                'creator_id' => 1,
                'created_at' => 1707095721,
                'updated_at' => 1708264148,
                'deleted_at' => 0,
                'children' => [
                    0 => [
                        'id' => 204,
                        'parent_id' => 205,
                        'permission_name' => '域名配置',
                        'route' => 'domain/config',
                        'icon' => '',
                        'module' => 'domain',
                        'permission_mark' => 'asyncTask',
                        'component' => '/domain/domainConfig/index.vue',
                        'redirect' => '',
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => 1707055975,
                        'updated_at' => 1708264148,
                        'deleted_at' => 0,
                    ],
                    1 => [
                        'id' => 212,
                        'parent_id' => 205,
                        'permission_name' => '域名解析',
                        'route' => 'records/:id/:name',
                        'icon' => '',
                        'module' => 'domain',
                        'permission_mark' => 'domainRecords',
                        'component' => '/domain/domainRecords/index.vue',
                        'redirect' => '',
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 2,
                        'sort' => 1,
                        'active_menu' => '/domain/domains',
                        'creator_id' => 1,
                        'created_at' => 1707299651,
                        'updated_at' => 1708264148,
                        'deleted_at' => 0,
                    ],
                    2 => [
                        'id' => 206,
                        'parent_id' => 205,
                        'permission_name' => '域名列表',
                        'route' => 'domains',
                        'icon' => '',
                        'module' => 'domain',
                        'permission_mark' => 'domains',
                        'component' => '/domain/domains/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => 1707096181,
                        'updated_at' => 1708264148,
                        'deleted_at' => 0,
                        'children' => [
                            0 => [
                                'id' => 211,
                                'parent_id' => 206,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'domain',
                                'permission_mark' => 'domains@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => 1707096181,
                                'updated_at' => 1708264148,
                                'deleted_at' => 0,
                            ],
                            1 => [
                                'id' => 207,
                                'parent_id' => 206,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'domain',
                                'permission_mark' => 'domains@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => 1707096181,
                                'updated_at' => 1708264148,
                                'deleted_at' => 0,
                            ],
                            2 => [
                                'id' => 209,
                                'parent_id' => 206,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'domain',
                                'permission_mark' => 'domains@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => 1707096181,
                                'updated_at' => 1708264148,
                                'deleted_at' => 0,
                            ],
                            3 => [
                                'id' => 208,
                                'parent_id' => 206,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'domain',
                                'permission_mark' => 'domains@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => 1707096181,
                                'updated_at' => 1708264148,
                                'deleted_at' => 0,
                            ],
                            4 => [
                                'id' => 210,
                                'parent_id' => 206,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'domain',
                                'permission_mark' => 'domains@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => 1707096181,
                                'updated_at' => 1708264148,
                                'deleted_at' => 0,
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
};
