<?php

use Illuminate\Database\Seeder;
use Modules\Common\Support\ImportPermissions;

return new class() extends Seeder {
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run(): void
    {
        $menus = $this->menus();

        ImportPermissions::import($menus);
    }

    public function menus(): array
    {
        return  [
            0 => [
                'id' => 778,
                'parent_id' => 0,
                'permission_name' => 'AI助手',
                'route' => '/ai',
                'icon' => 'paper-airplane',
                'module' => 'ai',
                'permission_mark' => '',
                'component' => '/layout/index.vue',
                'redirect' => '',
                'keepalive' => 1,
                'type' => 1,
                'hidden' => 1,
                'sort' => 17,
                'active_menu' => '',
                'creator_id' => 1,
                'created_at' => '2025-02-17 13:21',
                'updated_at' => '2025-04-01 09:28',
                'children' => [
                    0 => [
                        'id' => 797,
                        'parent_id' => 778,
                        'permission_name' => '智能体管理',
                        'route' => 'aiChatBots',
                        'icon' => '',
                        'module' => 'ai',
                        'permission_mark' => 'aiChatBots',
                        'component' => '/ai/aiChatBots/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-02-23 15:33',
                        'updated_at' => '2025-02-23 15:33',
                        'children' => [
                            0 => [
                                'id' => 802,
                                'parent_id' => 797,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiChatBots@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-23 15:33',
                                'updated_at' => '2025-02-23 15:33',
                            ],
                            1 => [
                                'id' => 798,
                                'parent_id' => 797,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiChatBots@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-23 15:33',
                                'updated_at' => '2025-02-23 15:33',
                            ],
                            2 => [
                                'id' => 800,
                                'parent_id' => 797,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiChatBots@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-23 15:33',
                                'updated_at' => '2025-02-23 15:33',
                            ],
                            3 => [
                                'id' => 799,
                                'parent_id' => 797,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiChatBots@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-23 15:33',
                                'updated_at' => '2025-02-23 15:33',
                            ],
                            4 => [
                                'id' => 801,
                                'parent_id' => 797,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiChatBots@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-23 15:33',
                                'updated_at' => '2025-02-23 15:33',
                            ],
                        ],
                    ],
                    1 => [
                        'id' => 779,
                        'parent_id' => 778,
                        'permission_name' => 'Ai提供商',
                        'route' => 'aiProviders',
                        'icon' => '',
                        'module' => 'ai',
                        'permission_mark' => 'aiProviders',
                        'component' => '/ai/aiProviders/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-02-17 13:21',
                        'updated_at' => '2025-02-17 13:21',
                        'children' => [
                            0 => [
                                'id' => 784,
                                'parent_id' => 779,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiProviders@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-17 13:21',
                                'updated_at' => '2025-02-17 13:21',
                            ],
                            1 => [
                                'id' => 780,
                                'parent_id' => 779,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiProviders@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-17 13:21',
                                'updated_at' => '2025-02-17 13:21',
                            ],
                            2 => [
                                'id' => 782,
                                'parent_id' => 779,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiProviders@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-17 13:21',
                                'updated_at' => '2025-02-17 13:21',
                            ],
                            3 => [
                                'id' => 781,
                                'parent_id' => 779,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiProviders@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-17 13:21',
                                'updated_at' => '2025-02-17 13:21',
                            ],
                            4 => [
                                'id' => 783,
                                'parent_id' => 779,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'ai',
                                'permission_mark' => 'aiProviders@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-02-17 13:21',
                                'updated_at' => '2025-02-17 13:21',
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
};
