<?php

use Illuminate\Database\Seeder;
use Modules\Common\Support\ImportPermissions;

return new class() extends Seeder {
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run(): void
    {
        $menus = $this->menus();

        ImportPermissions::import($menus);
    }

    public function menus(): array
    {
        return [
            0 => [
                'id' => 77,
                'parent_id' => 0,
                'permission_name' => '会员管理',
                'route' => '/member',
                'icon' => 'user',
                'module' => 'member',
                'permission_mark' => '',
                'component' => '/layout/index.vue',
                'redirect' => null,
                'keepalive' => 1,
                'type' => 1,
                'hidden' => 1,
                'sort' => 1,
                'active_menu' => '',
                'creator_id' => 1,
                'created_at' => '2023-11-20 07:51',
                'updated_at' => '2023-11-20 07:51',
                'children' => [
                    0 => [
                        'id' => 79,
                        'parent_id' => 77,
                        'permission_name' => '会员分组',
                        'route' => 'member/groups',
                        'icon' => '',
                        'module' => 'member',
                        'permission_mark' => 'memberGroups',
                        'component' => '/member/memberGroups/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2023-11-20 07:52',
                        'updated_at' => '2023-11-20 07:52',
                        'children' => [
                            0 => [
                                'id' => 94,
                                'parent_id' => 79,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'memberGroups@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:56',
                                'updated_at' => '2023-11-20 07:56',
                            ],
                            1 => [
                                'id' => 95,
                                'parent_id' => 79,
                                'permission_name' => '禁用/启用',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'memberGroups@enable',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 6,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:56',
                                'updated_at' => '2023-11-20 07:56',
                            ],
                            2 => [
                                'id' => 90,
                                'parent_id' => 79,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'memberGroups@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:56',
                                'updated_at' => '2023-11-20 07:56',
                            ],
                            3 => [
                                'id' => 92,
                                'parent_id' => 79,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'memberGroups@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:56',
                                'updated_at' => '2023-11-20 07:56',
                            ],
                            4 => [
                                'id' => 91,
                                'parent_id' => 79,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'memberGroups@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:56',
                                'updated_at' => '2023-11-20 07:56',
                            ],
                            5 => [
                                'id' => 93,
                                'parent_id' => 79,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'memberGroups@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:56',
                                'updated_at' => '2023-11-20 07:56',
                            ],
                        ],
                    ],
                    1 => [
                        'id' => 78,
                        'parent_id' => 77,
                        'permission_name' => '会员列表',
                        'route' => 'members',
                        'icon' => '',
                        'module' => 'member',
                        'permission_mark' => 'members',
                        'component' => '/member/members/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2023-11-20 07:52',
                        'updated_at' => '2023-11-20 07:52',
                        'children' => [
                            0 => [
                                'id' => 100,
                                'parent_id' => 78,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'members@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:57',
                                'updated_at' => '2023-11-20 07:57',
                            ],
                            1 => [
                                'id' => 101,
                                'parent_id' => 78,
                                'permission_name' => '禁用/启用',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'members@enable',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 6,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:57',
                                'updated_at' => '2023-11-20 07:57',
                            ],
                            2 => [
                                'id' => 96,
                                'parent_id' => 78,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'members@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:57',
                                'updated_at' => '2023-11-20 07:57',
                            ],
                            3 => [
                                'id' => 98,
                                'parent_id' => 78,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'members@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:57',
                                'updated_at' => '2023-11-20 07:57',
                            ],
                            4 => [
                                'id' => 97,
                                'parent_id' => 78,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'members@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:57',
                                'updated_at' => '2023-11-20 07:57',
                            ],
                            5 => [
                                'id' => 99,
                                'parent_id' => 78,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'member',
                                'permission_mark' => 'members@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2023-11-20 07:57',
                                'updated_at' => '2023-11-20 07:57',
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
};
