<?php

use Illuminate\Database\Seeder;
use Modules\Common\Support\ImportPermissions;

return new class() extends Seeder {
    /**
     * Run the seeder.
     */
    public function run(): void
    {
        $menus = $this->menus();

        ImportPermissions::import($menus);
    }

    public function menus(): array
    {
        return [
            0 => [
                'id' => 198,
                'parent_id' => 0,
                'permission_name' => '支付管理',
                'route' => '/pay',
                'icon' => 'currency-dollar',
                'module' => 'pay',
                'permission_mark' => '',
                'component' => '',
                'redirect' => '',
                'keepalive' => 1,
                'type' => 1,
                'hidden' => 1,
                'sort' => 1,
                'active_menu' => '',
                'creator_id' => 1,
                'created_at' => '2025-05-04 17:58',
                'updated_at' => '2025-05-04 17:58',
                'children' => [
                    0 => [
                        'id' => 199,
                        'parent_id' => 198,
                        'permission_name' => '支付宝支付',
                        'route' => 'alipay',
                        'icon' => '',
                        'module' => 'pay',
                        'permission_mark' => 'config',
                        'component' => '/pay/alipay/index.vue',
                        'redirect' => '',
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-05-04 17:58',
                        'updated_at' => '2025-05-04 17:58',
                        'children' => [
                            0 => [
                                'id' => 200,
                                'parent_id' => 199,
                                'permission_name' => '支付宝配置',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'config@alipay',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-04 17:58',
                                'updated_at' => '2025-05-04 17:58',
                            ],
                            1 => [
                                'id' => 201,
                                'parent_id' => 199,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'config@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-04 17:58',
                                'updated_at' => '2025-05-04 17:58',
                            ],
                            2 => [
                                'id' => 202,
                                'parent_id' => 199,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'config@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-04 17:58',
                                'updated_at' => '2025-05-04 17:58',
                            ],
                        ],
                    ],
                    1 => [
                        'id' => 203,
                        'parent_id' => 198,
                        'permission_name' => '微信支付',
                        'route' => 'wechat',
                        'icon' => '',
                        'module' => 'pay',
                        'permission_mark' => 'config',
                        'component' => '/pay/wechat/index.vue',
                        'redirect' => '',
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-05-04 17:58',
                        'updated_at' => '2025-05-04 17:58',
                        'children' => [
                            0 => [
                                'id' => 204,
                                'parent_id' => 203,
                                'permission_name' => '微信支付配置',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'config@wechat',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-04 17:58',
                                'updated_at' => '2025-05-04 17:58',
                            ],
                        ],
                    ],
                    2 => [
                        'id' => 205,
                        'parent_id' => 198,
                        'permission_name' => '银联支付',
                        'route' => 'unipay',
                        'icon' => '',
                        'module' => 'pay',
                        'permission_mark' => 'config',
                        'component' => '/pay/unipay/index.vue',
                        'redirect' => '',
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-05-04 17:58',
                        'updated_at' => '2025-05-04 17:58',
                    ],
                    3 => [
                        'id' => 206,
                        'parent_id' => 198,
                        'permission_name' => '抖音支付',
                        'route' => 'douyin',
                        'icon' => '',
                        'module' => 'pay',
                        'permission_mark' => 'config',
                        'component' => '/pay/douyin/index',
                        'redirect' => '',
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-05-04 17:58',
                        'updated_at' => '2025-05-04 17:58',
                    ],
                    4 => [
                        'id' => 303,
                        'parent_id' => 198,
                        'permission_name' => '订单管理',
                        'route' => 'order',
                        'icon' => '',
                        'module' => 'pay',
                        'permission_mark' => 'order',
                        'component' => '/pay/order/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-05-17 19:58',
                        'updated_at' => '2025-05-17 19:58',
                        'children' => [
                            0 => [
                                'id' => 305,
                                'parent_id' => 303,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'order@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-17 19:58',
                                'updated_at' => '2025-05-17 19:58',
                            ],
                            1 => [
                                'id' => 304,
                                'parent_id' => 303,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'order@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-17 19:58',
                                'updated_at' => '2025-05-17 19:58',
                            ],
                        ],
                    ],
                    5 => [
                        'id' => 306,
                        'parent_id' => 198,
                        'permission_name' => '退款管理',
                        'route' => 'orderRefund',
                        'icon' => '',
                        'module' => 'pay',
                        'permission_mark' => 'orderRefund',
                        'component' => '/pay/orderRefund/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-05-17 19:59',
                        'updated_at' => '2025-05-17 19:59',
                        'children' => [
                            0 => [
                                'id' => 308,
                                'parent_id' => 306,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'orderRefund@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-17 19:59',
                                'updated_at' => '2025-05-17 19:59',
                            ],
                            1 => [
                                'id' => 307,
                                'parent_id' => 306,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'pay',
                                'permission_mark' => 'orderRefund@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-05-17 19:59',
                                'updated_at' => '2025-05-17 19:59',
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
};
