<?php

use Illuminate\Database\Seeder;
use Modules\Common\Support\ImportPermissions;

return new class() extends Seeder {
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run(): void
    {
        $menus = $this->menus();

        ImportPermissions::import($menus);
    }

    public function menus(): array
    {
        return  [
            0 => [
                'id' => 342,
                'parent_id' => 0,
                'permission_name' => '邮件营销',
                'route' => '/mail',
                'icon' => 'envelope',
                'module' => 'mail',
                'permission_mark' => '',
                'component' => '/layout/index.vue',
                'redirect' => null,
                'keepalive' => 1,
                'type' => 1,
                'hidden' => 1,
                'sort' => 1,
                'active_menu' => '',
                'creator_id' => 1,
                'created_at' => '2025-08-13 18:41',
                'updated_at' => '2025-08-13 18:41',
                'children' => [
                    0 => [
                        'id' => 351,
                        'parent_id' => 342,
                        'permission_name' => '邮件发送',
                        'route' => 'send',
                        'icon' => '',
                        'module' => 'mail',
                        'permission_mark' => 'send',
                        'component' => '/mail/send/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-08-14 19:16',
                        'updated_at' => '2025-08-14 19:16',
                    ],
                    1 => [
                        'id' => 352,
                        'parent_id' => 342,
                        'permission_name' => '营销任务',
                        'route' => 'sendTask',
                        'icon' => '',
                        'module' => 'mail',
                        'permission_mark' => 'sendTask',
                        'component' => '/mail/sendTask/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-08-15 18:36',
                        'updated_at' => '2025-08-15 18:36',
                        'children' => [
                            0 => [
                                'id' => 357,
                                'parent_id' => 352,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'sendTask@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-15 18:36',
                                'updated_at' => '2025-08-15 18:36',
                            ],
                            1 => [
                                'id' => 353,
                                'parent_id' => 352,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'sendTask@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-15 18:36',
                                'updated_at' => '2025-08-15 18:36',
                            ],
                            2 => [
                                'id' => 355,
                                'parent_id' => 352,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'sendTask@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-15 18:36',
                                'updated_at' => '2025-08-15 18:36',
                            ],
                            3 => [
                                'id' => 354,
                                'parent_id' => 352,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'sendTask@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-15 18:36',
                                'updated_at' => '2025-08-15 18:36',
                            ],
                            4 => [
                                'id' => 356,
                                'parent_id' => 352,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'sendTask@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-15 18:36',
                                'updated_at' => '2025-08-15 18:36',
                            ],
                        ],
                    ],
                    2 => [
                        'id' => 343,
                        'parent_id' => 342,
                        'permission_name' => '基本设置',
                        'route' => '/setting',
                        'icon' => '',
                        'module' => 'mail',
                        'permission_mark' => 'setting',
                        'component' => '/mail/setting/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-08-13 18:41',
                        'updated_at' => '2025-08-13 18:41',
                    ],
                    3 => [
                        'id' => 344,
                        'parent_id' => 342,
                        'permission_name' => '邮件模板',
                        'route' => 'template',
                        'icon' => '',
                        'module' => 'mail',
                        'permission_mark' => 'template',
                        'component' => '/mail/template/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2025-08-14 18:51',
                        'updated_at' => '2025-08-14 18:51',
                        'children' => [
                            0 => [
                                'id' => 349,
                                'parent_id' => 344,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'template@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-14 18:51',
                                'updated_at' => '2025-08-14 18:51',
                            ],
                            1 => [
                                'id' => 350,
                                'parent_id' => 344,
                                'permission_name' => '禁用/启用',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'template@enable',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 6,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-14 18:51',
                                'updated_at' => '2025-08-14 18:51',
                            ],
                            2 => [
                                'id' => 345,
                                'parent_id' => 344,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'template@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-14 18:51',
                                'updated_at' => '2025-08-14 18:51',
                            ],
                            3 => [
                                'id' => 347,
                                'parent_id' => 344,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'template@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-14 18:51',
                                'updated_at' => '2025-08-14 18:51',
                            ],
                            4 => [
                                'id' => 346,
                                'parent_id' => 344,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'template@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-14 18:51',
                                'updated_at' => '2025-08-14 18:51',
                            ],
                            5 => [
                                'id' => 348,
                                'parent_id' => 344,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'mail',
                                'permission_mark' => 'template@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2025-08-14 18:51',
                                'updated_at' => '2025-08-14 18:51',
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
};
